### ISSUE TITLE
Standardize file extension for saved games

### ISSUE THREAD

**Issue by x-sheep** [chrisboyle/sgtpuzzles#242]
The app currently exports saved games with a `.sav` extension, which is already used by dozens of other games. If this could be changed to something more specific, other frontends could associate with the new file extension without also trying to open files it can't deal with.

**Comment by chrisboyle** [comment]
The difficulty here is every three-character extension is used (.puz in particular is a crossword format), and I don't know if there are any remaining users for whom using a longer extension would be problematic because of FAT filesystem issues. At least with .sav everyone understands it could be from many different games. Nevertheless, I could change it to e.g. .sgtpuzzles to be truly specific, and hope that FAT issues aren't really a problem these days...

**Comment by x-sheep** [comment]
I'm currently using `.puzzle` for the Windows RT and Windows Phone ports I'm working on. I don't think there's another program actively using `.puzzle`, but I could still change this to `.sgtpuzzles` if requested.

**Comment by chrisboyle** [comment]
https://www.google.co.uk/search?q=".puzzle"%20file%20extension lists a few. I think .sgtpuzzles is too long really, so am thinking of using .sgtp
