### ISSUE TITLE
Need escape route when generating a game with previous settings is slow

### ISSUE THREAD

**Issue by chrisboyle** [chrisboyle/sgtpuzzles#349]
Reported by Annatala Wolf. If you choose a game from the chooser and your previous game was completed, then we immediately generate another with the same settings. This can be slow, and you might not want to wait as long as you did on some previous occasion when you enthusiastically selected a very large board.

Clicking Cancel just dumps you back at the chooser with no way to correct the situation, short of resetting the entire app's settings. Perhaps after a few seconds an additional button could appear on that dialog or something? "Reset game type"? This may require dismissing and re-opening the dialog. :-/

**Comment by chrisboyle** [comment]
Delayed button looks doable: https://stackoverflow.com/questions/19358572/how-to-show-progress-dialog-button-dynamically-after-n-seconds-delay

**Comment by Dansiman** [comment]
Instead of fully resetting the game's parameters to defaults, it would be great if this delayed-appearance button could navigate to the game parameters screen as is. That way we could, e.g., just reduce the puzzle size by 1 or 2 and try again, to more easily find the optimal balance between puzzle size and generation time.

**Comment by chrisboyle** [comment]
I don't necessarily disagree, but in that case we would then need a sufficiently prominent reset-to-defaults button on the parameters screen, to make it really obvious how to get to a known-working state from there.
