### ISSUE TITLE
Add 2048

### ISSUE THREAD

**Issue by ascuccaro** [chrisboyle/sgtpuzzles#401]
Is there any chance to add 2048 to the list of games? It doesn't necessarily needs to use gestures to be played, gestures could be easily replaced with directional arrows (left, right, up, down).

**Comment by chrisboyle** [comment]
I'm not sure it really fits the aims of the collection as discussed at http://www.chiark.greenend.org.uk/~sgtatham/puzzles/devel/writing.html#writing-editorial - notice that the existing games tend to do all their randomness up front rather than having ongoing uncertainty. There may also be copyright concerns as that game was created relatively recently by a single identifiable author.

Having said all that, I just do the Android port, I am not the gatekeeper of what can appear in Simon's collection; take it up with him if you strongly disagree.
