### ISSUE TITLE
After 3/24/2019 update libpuzzlesgen.so missing

### ISSUE THREAD

**Issue by jraller** [chrisboyle/sgtpuzzles#461]
Error message is:

/data/app/name.boyle.chris.sgtpuzzles-9s5EfEeJtmvmvcTEspBKRA==/lib/arm64/libpuzzlesgen.so (No such file or directory)

When choosing new game after having solved a game.

**Comment by ffes** [comment]
I have exactly the same problem. After completing the game I got this error and it is impossible to generate a new one. Which seems logical given the filename in the error message.

![Screenshot_20190325-075453](https://user-images.githubusercontent.com/3225656/54901312-5ce52600-4ed6-11e9-92c3-4690b16a784d.jpg)

**Comment by mquevill** [comment]
It also happens even if you haven't completed a game.

**Comment by ffes** [comment]
Small clarification (just in case :wink:): this happens after updating to version 2019-03-25-0020-68363231 this morning.

**Comment by dean-e-peterson** [comment]
Same problem, but with filename /lib/arm/libpuzzlesgen.so instead of /lib/arm64... Happening only when generating a new puzzle, as opposed to completing a puzzle generated before the update.  Tested on multiple puzzle types with same result.

**Comment by bruzie** [comment]
Same with me. Tried Force stop and uninstall/reinstall, same result.

**Comment by chrisboyle** [comment]
I'm working on this but it's a bit of a mystery so far. It relates to Google Play's installation methods and the new Android App Bundle upload format, which I already used for the previous update without such widespread problems.

If you install https://chris.boyle.name/static/media/uploads/SGTPuzzles-2019-03-25-0020-68363231.apk which is the same version, you should find that works, because the installation method is different (it's larger because it contains all architectures).

More detail:

What's supposed to happen is Google ships a few smaller apks to your device e.g.
* base.apk
* split_config.en.apk
* split_config.x86.apk   (x86 or arm64 or arm etc. depending on what you have)
* split_config.xxhdpi.apk

In the failing cases, Google has shipped the right set of files, and the architecture-specific one (x86 in my example here) does contain the two files I need, but the device has not unpacked it for some reason. This differs from a manual APK install in which everything is immediately unpacked from that one APK.

**Comment by ffes** [comment]
@chrisboyle Thanks for the detailed explanation!!!

I just opted-in for the beta program and saw your 10:16 update. That works fine on my phone.

**Comment by chrisboyle** [comment]
@ffes Thanks, good to hear. That update is a monolithic APK upload, which thankfully Google still allows, for now. I will promote that to production, and then I can debug this App Bundle stuff less urgently, in an alpha channel with just me initially.

**Comment by jraller** [comment]
I updated from Google Play and the issue is resolved. Thank you and good luck with figuring out the new deployment methods.
