### ISSUE TITLE
Pearl: mechanising the constraints

### ISSUE THREAD

**Issue by yashpalgoyal1304** [chrisboyle/sgtpuzzles#505]
all but one of the conditions/constraints on the game [pearl]: are very VERY easy to be mechanised in theory (i.e. not saying wrt implementation in code). 
* Black circle has to be a bend, but str8 thereafter, so, 2×2 L pivoted at it.
* White has to be a str8, so, 3×1 straight line, centered at it. 
* Make these things rotatable - similar to things in [net] or [twiddle]
* The one condition left will be that white's straight has to turn at one of its ends, that cant be mechanised beautifully as far as i can think, but it's not required to be mechanised either.

i know it's not super important thing, but just thought to get more eyes on it

[pearl]: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/pearl.html
[twiddle]: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/twiddle.html
[net]: https://www.chiark.greenend.org.uk/~sgtatham/puzzles/js/net.html

**Comment by yashpalgoyal1304** [comment]
while playing palisade, i realised that this logic of thinking may bleed into many games and thus, either create inconsistency, or create lots of work without any significant gain. so, closing it. it was nice to thinking about this, but not much practical.

**Comment by goyalyashpal** [comment]
while playing slant, i felt that rather than providing this on whole board together... this can be (experimentally) given as a control option for individual element.

so say, choose this contol option, and apply it on some "square" (in slant parlance) and it provide a template which satisfies _just_ the "specification" of that square i.e. the _obvious_ game constraints; and then option to transform (like rotate) that template. So in slant, sq labelled 4 will get 4 outwards diagonals; sq(0) will get ring like diagonals and so on.

this per-element template, while staying non-obtrusive, can also help users to navigate some tough-y corners of a game while getting started, and get better taste of the game at a smoother learning curve.

and it feels even better to _think about_, so much so that i want to experiment with implementing it.
