### ISSUE TITLE
Turkish "no summary available" & crash on some games

### ISSUE THREAD

**Issue by mr-mygdon** [chrisboyle/sgtpuzzles#538]
Some games are unplayable. (Bridges, Dominosa, Fifteen, Filling, Inertia, Mines etc.) Phone : Galaxy s8+

**Comment by chrisboyle** [comment]
Hi, thanks for your report: what happens when you try to play these games?

**Comment by baduann** [comment]
I've been experiencing the same thing, app crashes when o try to open games that say (no summary available)

**Comment by chrisboyle** [comment]
@baduann That message shouldn't appear. This suggests missing resources, and is not something most people are experiencing. Could you please try reinstalling the app? Oh, and maybe check your device isn't extremely low on space first, in case that is affecting the installation.

Thanks

**Comment by baduann** [comment]
I reinstalled the app after opening up some space and still having the same problem

**Comment by mr-mygdon** [comment]
Hi..
I installed the old version from f-droid source and it works fine.  After updating from the google play store, some games crash again...

**Comment by chrisboyle** [comment]
This is very confusing. It's in [these lines here](https://github.com/chrisboyle/sgtpuzzles/blob/2022-04-26-0739-c43a34fb/app/src/main/java/name/boyle/chris/sgtpuzzles/GameChooser.java#L161-L165) that "(no summary available)" (aka `R.string.no_desc`) is chosen and that means it can't find e.g. `R.string.desc_bridges`. The resources live in [this file](https://github.com/chrisboyle/sgtpuzzles/blob/2022-04-26-0739-c43a34fb/app/src/main/res/values/strings.xml#L156-L196) and none of them are qualified by language or anything, so they should all just always be installed and available.

I've so far failed to think of anything that's different about that specific list of games compared to the others.

A few questions in case they lead to clues...

* @baduann Did you also install from Google Play rather than some other way?
* Are the icons for those puzzles missing too?
* Do the names show up correctly e.g. "Light Up"?
* What version of Android are you running?
* Have you tried it on any other devices?
* Can you think of anything unusual about the affected devices or their settings?
* @mr-mygdon @baduann Assuming you see the "Puzzles has stopped" dialog, have you tapped "Send feedback"? This should send me a stacktrace in the Google Play Console. @baduann What model is your phone? (This will help me find any crash reports in the console.)

**Comment by chrisboyle** [comment]
OH! You don't happen to both have your language set to Turkish do you? And @baduann are you sure about Cube? Because other than Cube, you have listed exactly the Puzzles whose names contain the letter `i`, and I've done some lowercase/uppercase operations that could hit [this well-known problem](https://mattryall.net/blog/the-infamous-turkish-locale-bug) where the letter i is involved. Easily fixed if it is that.

**Comment by mr-mygdon** [comment]
![Uploading Screenshot_20220429-192818_Puzzles.jpg…]()

**Comment by chrisboyle** [comment]
@baduann Great! Thank you, I will ship a new version soon that fixes this.

@mr-mygdon "Missing Storage Acess Framework" is a different issue. Devices running Android 4.4 and higher are supposed to include this framework that I can call when I want to load or save files, which lets you use either local storage or Google Drive, Dropbox, whatever you have installed. (Btw the 2022 versions of Puzzles require Android 4.4 or higher, 2019 was 4.1.) This error is reported when that framework is missing despite 4.4+, which is unusual; it should be part of Android. You could try installing a file manager (or a different file manager) which may also provide this capability. Beware, there are a lot of scammy ad-filled file managers out there :-(

**Comment by mr-mygdon** [comment]
Thank you chris, great job..
