### ISSUE TITLE
Pattern clues are false

### ISSUE THREAD

**Issue by MonsterRosh** [chrisboyle/sgtpuzzles#560]
The clue numbers along the outside edge are false. The puzzle is not solvable by following  the clues.

**Screenshots**
![image](https://user-images.githubusercontent.com/111220016/184527555-689f6783-bfc9-46c7-ac08-cfc4ea68181f.png)

 - Phone/tablet model: android Galaxy a52 5g
 - Android version: 12
 - App Version 2022-05-21-1809-c43a34fb

**Additional context**
Absolutely  love this app. Thank you so much for your hard work 💜

**Comment by mquevill** [comment]
It looks like you are only seeing the rightmost column of numbers for the horizontal rows. Is there a chance that you were zoomed in so that the other clues were hidden?

If this is the case, perhaps there should be some sort of indication that the user is zoomed in, in case they are missing clues or other information in the game.

**Comment by MonsterRosh** [comment]
Omg I'm glad I was just being stupid and the game wasn't broken :) you are correct, I must have accidently zoomed in at one point. Thank you!

**Comment by yashpalgoyal1304** [comment]
this issue can be closed
