### ISSUE TITLE
"Map" bug

### ISSUE THREAD

**Issue by i-d-d** [chrisboyle/sgtpuzzles#574]
**Describe the bug**
"Map" zones are filled with dots instead of colours

**Expected behavior**
Some time ago this game worked fine and zones that player chooses were just filled with colour, but at some point it started looking like this:

**Screenshots**
![IMG_20221126_101201.jpg](https://user-images.githubusercontent.com/90091936/204076957-5c9458b1-562a-442f-bc69-35ca9b598e9f.jpg)

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: OnePlus 9R
 - Android version: 12
 - App version: 2022-05-21-1809-c43a34fb

**Additional context**
Despite this little bug app is great! :)

**Comment by i-d-d** [comment]
UPD: it can be fixed by switching "Arrow keys in Map" in settings, but it still looks weird

**Comment by JupiLogy** [comment]
Hi @i-d-d , this is expected behaviour.

The dots act as "guesses" and allow the user to fill multiple possible colours for each region, a lot like the "pencil marks" in sudoku.

**Comment by chrisboyle** [comment]
@i-d-d Specifically, this is happening because you've pressed the "swap press and long press" button, which is highlighted at the bottom of your screenshot, looking like ". / -". This button makes it easier to quickly access alternate actions in some games, for which other platforms use the right mouse button (or right button and drag in this case), but occasionally people do press it accidentally.

**Comment by chrisboyle** [comment]
@i-d-d (just press that button again to switch back)

**Comment by i-d-d** [comment]
@JupiLogy
Oh, I noticed that there are no warnings when two zones with the same colour are next to each other, but I thought it was a part of a bug)
Thanks for a quick response anyway, your app is one of the best puzzle apps that I've seen!)
