### ISSUE TITLE
Adding more games

### ISSUE THREAD

**Issue by jjbali12** [chrisboyle/sgtpuzzles#596]
Hello Chris!

I cannot build the latest version of "Simon Tatham Puzzles", because i counter many errors. My plan is to add some "unreleased" games into that app, but i said that "i counter many errors", so can you build the app for me with many game?
Also, i sent a mail from your account (johnnollas5@gmail.com)

**Comment by jjbali12** [comment]
Can you add this games on your app?

[sgt-puzzles-aho-extensions-main.zip](https://github.com/chrisboyle/sgtpuzzles/files/11071337/sgt-puzzles-aho-extensions-main.zip)
[sgtpuzzles-extended-master.zip](https://github.com/chrisboyle/sgtpuzzles/files/11071339/sgtpuzzles-extended-master.zip)
[puzzles-unreleased-master.zip](https://github.com/chrisboyle/sgtpuzzles/files/11071340/puzzles-unreleased-master.zip)

**Comment by JupiLogy** [comment]
Can you post the errors you're receiving?

**Comment by chrisboyle** [comment]
A few thoughts: firstly these appear to be downloads of the following github repositories. In this situation it's generally better to link to the repository rather than downloading and uploading a snapshot.

* https://github.com/Anders-Holst/sgt-puzzles-aho-extensions
* https://github.com/SteffenBauer/sgtpuzzles-extended
* https://github.com/x-sheep/puzzles-unreleased

The good news is they all appear to keep the same MIT licence as upstream and this repo, so licensing does not prevent them being included.

The problem I have is that they're variously described as "unfinished", in which case I want to hear from their authors about what's unfinished (as well as reviewing the code myself), or having "not made it into the collection", suggesting Simon might have declined them for some reason, and if so I want to hear from their authors and/or Simon about why. I aim to keep the same high standards of quality and consistency in the Android port as Simon has for the original collection. Any games that meet those standards should probably be included in Simon's repo for all platforms, and then I'll pick them up from there.

**Comment by jjbali12** [comment]
"CreateProcess error=2", it always appear even the git is correctly located.

**Comment by jjbali12** [comment]
Can you make a build and send the source code?

**Comment by SteffenBauer** [comment]
> The problem I have is that they're variously described as "unfinished", in which case I want to hear from their authors about what's unfinished (as well as reviewing the code myself), or having "not made it into the collection", suggesting Simon might have declined them for some reason, and if so I want to hear from their authors and/or Simon about why. 

I am the author of one of those new game collections. I had mailed with Simon on various of those game extensions / new games. Simon's reasons to not include those were varied. For example he rejected the solving extensions of Solo (press a number to highlight the corresponding numbers / pencils marks in the grid, a feature that was asked for the android port several times in the issue tracker here) because he wanted to keep the puzzling experience minimalistic and clean. For the extended generator of Undead I didn't receive an answer. To be fair, Simon is very busy, and gets surely a lot of mail. So in the end, I just decided to put my game extensions to a GitHub repository so that other people can at least get the source code and compile them by themselves.

I created years ago even my own compiled Android app, including my new games and the games of X-Sheep, so it works principally. Unfortunately, with the big refactoring it would take too much new work to compile it again to an app, which I currently don't have.

In the end, I totally agree with Chris here. As the android app is among the device ports list on the official SGT puzzle page, it should include those puzzles that Simon deemed worthy to be included in his collection. I hope that Simon will find some time to look into these additional repositories, and include some new puzzles. In my personal opinion, there are definitely some that are of the quality that Simon expects (Boats from X-Sheep for example)

**Comment by SteffenBauer** [comment]
> where's the source code of your extension(s)?
Well, among the links that Chris posted here in this thread?
https://github.com/SteffenBauer/sgtpuzzles-extended

**Comment by jjbali** [comment]
I already downloaded it but i cannot compile the app because of the errors,
what will be the version of android studio should i use?

**Comment by SteffenBauer** [comment]
Those won't work with the current android port. It will take a lot of adjusting work.

**Comment by jjbali** [comment]
Aside from that, what will be the version of android studio should i use to
compile the app?

**Comment by SteffenBauer** [comment]
A second remark on
>suggesting Simon might have declined them for some reason, and if so I want to hear from their authors and/or Simon about why. 

After buying an eReader (pocketbook brand), I took the time to port the puzzle collection to it. I contacted Simon and asked him if he could include a link to the port on the list of device ports on the official SGT puzzle site.
Simon declined, exactly for the reason that I had included the unfinished puzzles (group and sokoban), and I assume also because I included the inofficial puzzles.
So an official device port should really only include official puzzles, and one of the inofficial puzzles should only be added to the android port after having added to Simons official puzzle collection.

**Comment by x-sheep** [comment]
> So an official device port should really only include official puzzles, and one of the inofficial puzzles should only be added to the android port after having added to Simons official puzzle collection.

This is also the reason I haven't included any of the unofficial puzzles in my UWP port.

Of my own collection, [Ascent](https://github.com/x-sheep/puzzles-unreleased/blob/master/docs/ascent.md) has to be my favorite. All of the puzzles except the ones I've listed under "Abandoned" are playable. In either case, I'm happy if Simon wants to add any of them to his collection, even without contacting me first. As said before, everything is MIT licensed, so asking me for permission isn't necessary.

**Comment by goyalyashpal** [comment]
at this point, it pretty much seems that there should be some "community" version of sgt puzzles lol.

similar to how there's [manim community] took by community from grant sanderson's [personal manim][g-manim]

[manim community]: https://github.com/ManimCommunity/manim/
[g-manim]: https://github.com/3b1b/manim

**Comment by goyalyashpal** [comment]
searching for [puzzles sgt] there are 28 repos in results, most of which are stale; there were some attempts of mirrors too - but even those have gone stale.

[puzzles sgt]: https://github.com/search?q=puzzles+sgt&type=repositories&s=updated&o=desc

**Comment by JupiLogy** [comment]
Be the change you want to see in the world, and make a fork where you incorporate lots of community suggestions? Or, open issues on those existing forks. The branch might be stale but the developers may well be active.

**Comment by chrisboyle** [comment]
It seems like the discussion reached a conclusion without a convincing case for including more puzzles than Simon does, so I'm closing this, but best of luck with the various forks.
