### ISSUE TITLE
Bridges Custom Mode

### ISSUE THREAD

**Issue by divi0001** [chrisboyle/sgtpuzzles#602]
**Describe the bug**
I dont know if i am completely dumb, or this is a bug

**To Reproduce**
1. Open Bridges
2. New Game -> Custom
3. 25x25
4. Difficulty Hard
5. max bridges per direction: 4

I tried to solve:
Attachment:
![Screenshot_20230430-200650](https://user-images.githubusercontent.com/106699019/235369557-62abf206-37a4-47ed-98ed-918bc08b6b68.png)

**Expected behavior**
This is the part where either me is dumb, or this is the bug, that the puzzle can not be solved

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: [Pixel 6]
 - Graphene OS (Based on Android 13)
 - App version [idk latest?]

**Comment by JupiLogy** [comment]
Please can you provide the seed for the game state in the picture? You can also use "show solution" for a sanity check to see how the app expects the solution to look.

**Comment by mquevill** [comment]
This is not a bug in the code. Something must have gone wrong when you were solving it.

These are the changes needed to get the actual solution (red means remove this line, blue means add this line):
![image](https://user-images.githubusercontent.com/17033543/235371489-914b8a37-b1ce-406c-8417-477c89a1a80e.png)
You can verify this solution compared to yours, since the red 4 now has 2 additional lines, but every other number has a net zero (+1 line and -1 line).

**Comment by chrisboyle** [comment]
This looks resolved; if anything is still unclear then do reopen and attach a save file (use the Save or Share options)
