### ISSUE TITLE
Map: document that starting colours can't be removed

### ISSUE THREAD

**Issue by TobiasOscar** [chrisboyle/sgtpuzzles#624]
**Describe the bug**
Dragging from either an empty area or the border does not remove an areas color.

**To Reproduce**
1. Go to 'Map'
2. Start or load a game
3. Try to drag an empty area over an already filled area
4. Black or white dot drops, but color doesn't reset

**Expected behavior**
The color should be cleared.

**Screenshots**
If applicable, add screenshots to help explain your problem. You can also attach a saved game (checkerboard menu -> Save or Share).

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: Galaxy Tab A (2019) [SM-T510]
 - Android version: 11
 - App version:  2023-10-15-1359-2d9e414e

**Additional context**
[ERROR_Map_No_Color_Remove.sgtp.TXT](https://github.com/chrisboyle/sgtpuzzles/files/13196985/ERROR_Map_No_Color_Remove.sgtp.TXT)

**Comment by chrisboyle** [comment]
@TobiasOscar Hi, thanks for your report. You can't remove colours from the regions that have them at the start; this is an intentional part of the game. I now realise the instructions don't explicitly say that (though they do say it makes the solution unique), which makes this a documentation bug.

It would also be an improvement if those regions were marked in some way, which we already have an issue for: #224.

**Comment by TobiasOscar** [comment]
Uhg, my bad.  Sorry for the false alarm.
