### ISSUE TITLE
Towers bugging 

### ISSUE THREAD

**Issue by Wcsweet** [chrisboyle/sgtpuzzles#655]
Buttons are pressing other numbers when unprompted.
I think it might be lagging reading a screen touch and reads them all at once.
Makes game super unplayable even in easy 4x4 mode.

Load game, when putting pencil marks multiple other buttons are pressed other than the one you want, pressing 4 also presses 1 or undo

I expected to play like normal and add pencil marks as I figured out the tower numbers but I couldn't keep my numbers straight cause it would undo numbers I needed.

Google Pixel 6a
Version 2024-03-29-2245-fd304c53

**Additional context**

**Comment by chrisboyle** [comment]
There have been no other reports of this; given the large number of installations this suggests there might just be an issue with your touchscreen. You can find out using a developer setting: in your phone's settings, go to System / Developer options / Pointer location and turn it on. If developer options doesn't show, go to About phone and tap on the build number repeatedly.

This will show you if your screen thinks it's receiving taps/swipes when there are none. If so, this isn't an app-specific problem as Puzzles can only do what the OS / touchscreen tells it. On the other hand, if the traces show up generally, but you can see Puzzles acting without such traces, then that would suggest a bug here, but again it would have to be something vanishingly uncommon since nobody else has reported it.

Reopen if you can verify it as above, and ideally attach a screen recording so I can see the specifics.

Thanks
