### ISSUE TITLE
Wrong solution

### ISSUE THREAD

**Issue by NitroMdX** [chrisboyle/sgtpuzzles#658]
**Describe the bug**
Mines are located top right without any nearby numbers

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You can also attach a saved game (checkerboard menu -> Save or Share).

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: [e.g. Pixel 6]
 - Android version: [e.g. 12]
 - App version [e.g. 2022-01-02-1a2b3c4d]

**Additional context**

**Comment by chrisboyle** [comment]
Hi, it looks like you stopped filling in the bug report template after the first line, which means unfortunately I don't have enough information to help you. In particular, for this kind of bug report I would need to see a saved game file from when it happened (checkerboard menu -> Save) or at least a screenshot showing the problem, in order to make any progress.

**Comment by chrisboyle** [comment]
Closing as incomplete. Reopen if you can attach a saved game file or screenshot.
