### ISSUE TITLE
enable discussions in project settings and information sought about a new hanjie variety with less clues

### ISSUE THREAD

**Issue by john-peterson** [chrisboyle/sgtpuzzles#659]
# enable discussions

there is a new discussion section that you can enable in project settings. it allows comment replies and other improvements over issues. i have to read many things before I start my own work and this forum can assist with that

A separate section for discussion would be ideal for that but you have to enable it in project settings 

# hanjie variation with less clues 

i am gathering information about a hanjie variation that is superficially similar but with less clues. with two clues many of the same techniques apply. but there is even a single clue version. originally every segment has a clue for a total of many clues per line

it is called tile paint on the Wikipedia page for nono gram. i am wondering when it first appeared in nikoli and what they call it

conceptis call it cross pix on android and the ambiguous name "pixel" in their german magazine

i need to know if there are any existing public tools for this puzzle or if i have to start from scratch
 

# use hanjie validation as hint

 hal labs has included the validation tool in the game play. it first appeared in their zelda themed picross. i have not seen any android version with this feature. the iterator stops at the first solvable line and mark it for the player. this will prevent getting stuck without removing the challenge 

i will try to create a patch for this using the validator in this collection if it can be made to iterate through the puzzle and highlight solvable lines

# protected games

i like the pushmo/crashmo games but for ten years apparently no one has been able to bypass the protection for copying this game idea

can you tell me something more about popular protected games and if they can be reproduced

it is possible that they have not been popular enough or too complicated to program 

# cli

i am also wondering if anyone has seen a mouse enabled puzzle for the terminal. i would be interested to see it as a proof of concept for a terminal interface for grid based games

**Comment by chrisboyle** [comment]
Hi, thanks for your message.

I know about the Discussions option, but unfortunately I don't have time to moderate a discussion forum, nor is there anyone I trust enough who has time to do it for me. With that context I feel it would be irresponsible of me to enable Discussions, and equally so to endorse any specific forum elsewhere. I'll stick to receiving bugs and feature requests that are within the scope of this Android port, via this Issues section.

On your points about Hanjie, that sounds like a variation of Pattern. I think further variations of it could potentially fit in the collection, in Pattern or separately, but this comes under upstream development, and is not something I personally have time to work on any time soon. I've written a [readme file](https://github.com/chrisboyle/sgtpuzzles/blob/main/README.md) describing goals/non-goals for this project. Here is [Simon's page for the upstream project](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/), including a feedback section at the bottom, if you want to discuss new games/variants with him.

Copying existing commercial games that are more credibly owned by one company (rather than the widely known and often re-implemented traditional ones here) is not something I want to get involved with.

It might be interesting to add a UI within the upstream project to play within a terminal, but again that would not be for this Android project and not something I have time to work on.

One last thing: it would help in future to put each topic in its own github issue, so the status of different ideas can be tracked separately.

Thanks, and sorry I couldn't be of more assistance.
